# Generated by Django 4.1.3 on 2023-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurСlints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('PhoneNumber', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Region', models.CharField(max_length=120)),
            ],
        ),
    ]
