# Generated by Django 4.1.3 on 2023-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourсlints',
            name='Email',
            field=models.EmailField(max_length=120),
        ),
    ]
