# Generated by Django 4.1.3 on 2023-05-15 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_ourсlints_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourсlints',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='ourсlints',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
